// Celtics player dataset for RUSSELL trivia game
// heightIn = height in inches (for numeric comparison)
// allStar = All-Star selections while a member of the Celtics
export const PLAYERS = [
  { name: "Bill Russell", position: ["C"], number: 6, heightIn: 82, heightStr: "6'10\"", debut: 1956, allStar: 12 },
  { name: "Bob Cousy", position: ["PG"], number: 14, heightIn: 73, heightStr: "6'1\"", debut: 1950, allStar: 13 },
  { name: "John Havlicek", position: ["SG", "SF"], number: 17, heightIn: 77, heightStr: "6'5\"", debut: 1962, allStar: 13 },
  { name: "Larry Bird", position: ["SF"], number: 33, heightIn: 81, heightStr: "6'9\"", debut: 1979, allStar: 12 },
  { name: "Kevin McHale", position: ["PF"], number: 32, heightIn: 82, heightStr: "6'10\"", debut: 1980, allStar: 7 },
  { name: "Robert Parish", position: ["C"], number: 0, heightIn: 84, heightStr: "7'0\"", debut: 1980, allStar: 9 },
  { name: "Dennis Johnson", position: ["PG", "SG"], number: 3, heightIn: 76, heightStr: "6'4\"", debut: 1983, allStar: 1 },
  { name: "Danny Ainge", position: ["PG", "SG"], number: 44, heightIn: 77, heightStr: "6'5\"", debut: 1981, allStar: 1 },
  { name: "Bill Sharman", position: ["SG"], number: 21, heightIn: 73, heightStr: "6'1\"", debut: 1951, allStar: 8 },
  { name: "Sam Jones", position: ["SG"], number: 24, heightIn: 76, heightStr: "6'4\"", debut: 1957, allStar: 5 },
  { name: "Tom Heinsohn", position: ["PF"], number: 15, heightIn: 79, heightStr: "6'7\"", debut: 1956, allStar: 6 },
  { name: "Dave Cowens", position: ["C"], number: 18, heightIn: 81, heightStr: "6'9\"", debut: 1970, allStar: 8 },
  { name: "Jo Jo White", position: ["PG"], number: 10, heightIn: 75, heightStr: "6'3\"", debut: 1969, allStar: 7 },
  { name: "Paul Pierce", position: ["SF"], number: 34, heightIn: 79, heightStr: "6'7\"", debut: 1998, allStar: 10 },
  { name: "Ray Allen", position: ["SG"], number: 20, heightIn: 77, heightStr: "6'5\"", debut: 2007, allStar: 2 },
  { name: "Kevin Garnett", position: ["PF", "C"], number: 5, heightIn: 83, heightStr: "6'11\"", debut: 2007, allStar: 2 },
  { name: "Rajon Rondo", position: ["PG"], number: 9, heightIn: 73, heightStr: "6'1\"", debut: 2006, allStar: 3 },
  { name: "Antoine Walker", position: ["PF", "SF"], number: 8, heightIn: 80, heightStr: "6'8\"", debut: 1996, allStar: 3 },
  { name: "Nate Archibald", position: ["PG"], number: 7, heightIn: 73, heightStr: "6'1\"", debut: 1978, allStar: 3 },
  { name: "Reggie Lewis", position: ["SG", "SF"], number: 35, heightIn: 79, heightStr: "6'7\"", debut: 1987, allStar: 1 },
  { name: "Cedric Maxwell", position: ["SF", "PF"], number: 31, heightIn: 80, heightStr: "6'8\"", debut: 1977, allStar: 0 },
  { name: "Isaiah Thomas", position: ["PG"], number: 4, heightIn: 69, heightStr: "5'9\"", debut: 2015, allStar: 2 },
  { name: "Jayson Tatum", position: ["SF"], number: 0, heightIn: 80, heightStr: "6'8\"", debut: 2017, allStar: 6 },
  { name: "Jaylen Brown", position: ["SG", "SF"], number: 7, heightIn: 78, heightStr: "6'6\"", debut: 2016, allStar: 4 },
  { name: "Al Horford", position: ["C", "PF"], number: 42, heightIn: 81, heightStr: "6'9\"", debut: 2016, allStar: 0 },
  { name: "Gordon Hayward", position: ["SF"], number: 20, heightIn: 79, heightStr: "6'7\"", debut: 2017, allStar: 0 },
  { name: "Marcus Smart", position: ["PG", "SG"], number: 36, heightIn: 75, heightStr: "6'3\"", debut: 2014, allStar: 0 },
  { name: "Kyrie Irving", position: ["PG"], number: 11, heightIn: 74, heightStr: "6'2\"", debut: 2017, allStar: 2 },
  { name: "Brian Scalabrine", position: ["PF"], number: 44, heightIn: 81, heightStr: "6'9\"", debut: 2005, allStar: 0 },
  { name: "Bill Walton", position: ["C"], number: 5, heightIn: 83, heightStr: "6'11\"", debut: 1985, allStar: 0 },
  { name: "Dino Radja", position: ["PF", "C"], number: 40, heightIn: 83, heightStr: "6'11\"", debut: 1993, allStar: 0 },
  { name: "Rick Fox", position: ["SF"], number: 44, heightIn: 79, heightStr: "6'7\"", debut: 1991, allStar: 0 },
  { name: "Dee Brown", position: ["PG"], number: 7, heightIn: 73, heightStr: "6'1\"", debut: 1990, allStar: 0 },
  { name: "Vin Baker", position: ["PF", "C"], number: 42, heightIn: 83, heightStr: "6'11\"", debut: 1999, allStar: 0 },
  { name: "Walter McCarty", position: ["PF"], number: 24, heightIn: 82, heightStr: "6'10\"", debut: 1996, allStar: 0 },
  { name: "Tony Allen", position: ["SG", "SF"], number: 42, heightIn: 76, heightStr: "6'4\"", debut: 2004, allStar: 0 },
  { name: "Glen Davis", position: ["PF"], number: 11, heightIn: 81, heightStr: "6'9\"", debut: 2007, allStar: 0 },
  { name: "Jeff Green", position: ["SF", "PF"], number: 8, heightIn: 80, heightStr: "6'8\"", debut: 2011, allStar: 0 },
  { name: "Avery Bradley", position: ["SG"], number: 0, heightIn: 74, heightStr: "6'2\"", debut: 2010, allStar: 0 },
  { name: "Terry Rozier", position: ["PG"], number: 12, heightIn: 73, heightStr: "6'1\"", debut: 2015, allStar: 0 },
  { name: "Jrue Holiday", position: ["PG", "SG"], number: 4, heightIn: 75, heightStr: "6'3\"", debut: 2024, allStar: 0 },
  { name: "Derrick White", position: ["PG", "SG"], number: 9, heightIn: 76, heightStr: "6'4\"", debut: 2022, allStar: 1 },
  { name: "Robert Williams III", position: ["C"], number: 44, heightIn: 81, heightStr: "6'9\"", debut: 2018, allStar: 0 },
  { name: "Marcus Morris", position: ["PF"], number: 13, heightIn: 80, heightStr: "6'8\"", debut: 2019, allStar: 0 },
  { name: "Evan Turner", position: ["SG"], number: 11, heightIn: 79, heightStr: "6'7\"", debut: 2014, allStar: 0 },
  { name: "Paul Silas", position: ["PF"], number: 35, heightIn: 79, heightStr: "6'7\"", debut: 1972, allStar: 1 },
  { name: "Don Nelson", position: ["SF", "PF"], number: 19, heightIn: 78, heightStr: "6'6\"", debut: 1965, allStar: 0 },
  { name: "Frank Ramsey", position: ["SF", "SG"], number: 23, heightIn: 75, heightStr: "6'3\"", debut: 1954, allStar: 0 },
  { name: "Satch Sanders", position: ["SF", "PF"], number: 16, heightIn: 78, heightStr: "6'6\"", debut: 1960, allStar: 0 },
  { name: "K.C. Jones", position: ["PG"], number: 25, heightIn: 73, heightStr: "6'1\"", debut: 1958, allStar: 0 },
  { name: "Don Chaney", position: ["SG"], number: 12, heightIn: 77, heightStr: "6'5\"", debut: 1968, allStar: 0 },
];
